import './About.css'

export const About = () => {
  return (
    <div className="about">
      <section className="section">
        <div>Hi, I'm Mateusz. I'm an aspiring front-end developer currently focused on continuous growth and gaining a thorough understanding of the principles of software development. My immediate goal is to join a community of ambitious individuals eager for development, where I can enhance my skills and learn about various aspects of web development that I haven't had the opportunity to explore yet. In the future, I aspire to create applications that significantly improve people's lives on a large scale. I hope that a future role as a front-end developer will allow me to refine my skills, contribute to the team with my interesting personality, and understand the evolving world of technology. I believe that my approach to work and learning enables me to bring substantial value to any project I have the pleasure of working on.</div>
        <img className="my-img" src="/public/placeholder-me.jpg" alt="picture of me" />
      </section>
      <section className="section">
        <img src="/public/clipboard-list.svg" />
        <div style={{ textAlign: "end" }}>Immediately after completing high school at Economic Technical School No. 1 in Bydgoszcz, specializing in financial-credit analysis, I started working as an accountant, being the sole accountant in the company, working continuously for 4.5 years until the end of 2023. In this position, I was constantly compelled to improve my work by optimizing even the smallest tasks assigned to me. Maximizing the efficiency of my work, I decided that I would like to optimize and automate work in another way, creating much more complex programs than before in spreadsheets or scripts in accounting software. This decision sparked my interest in programming as a hobby and a possible future career. During this period, I also undertook teaching responsibilities at the Higher Banking School in Bydgoszcz, where I successfully completed a bachelor's degree in Finance and Accounting.</div>
      </section>
      <section className="section">
        <div>My main hobbies currently revolve around programming, computer games, and the natural sciences. I would consider myself a "Sunday" enthusiast of physics, chemistry, and biology. In my free time, during meals, or while traveling by bus or train, I love delving into literature that expands my knowledge of the universe and the matter that surrounds us. I enjoy exploring topics down to the simplest amino acids, elements, or quarks to fully understand the composition of everything I encounter daily. Computer games have led me to observe certain dependencies. A must happen A for B to happen afterward. Since childhood, I've been curious about how this entire network of connections operates. Finally, starting to write basic code in JavaScript, I grasped how computer engineering works. This amalgamation of seemingly unrelated fields has allowed me to continuously experience the world of programming, making it my number one hobby for almost a year already.</div>
        <img src="/public/laptop.svg" />
      </section>
      <section className="section">
        <img src="/public/hourglass.svg" />
        <div style={{ textAlign: "end" }}>I began my journey into programming in early 2023 when I realized that I couldn't endlessly optimize my work within the constraints of the accounting industry regulated by the accounting law. During a casual conversation with a close friend, he recommended trying my hand at programming. He provided me with some tips to expedite the initial process and build a strong foundation. Subsequently, I started learning using various tools such as YouTube, documentation, and simple courses or educational games that thoroughly explained fundamental concepts. Today, I feel confident enough to embark on a serious commercial project. I believe I've gained flexibility that allows me to approach a given problem from multiple perspectives and implement features in the most code-friendly way. I am aware that my code is not flawless, but possessing a tremendous desire for self-improvement, I am confident that I will eventually be able to build almost perfect applications.</div>
      </section>
      <section className="section">
        <div>In summary, a few words about myself. On a daily basis, I engage in an internal battle, constantly toggling my thinking between abstraction and pragmatism. On one hand, I am a creative individual, aspiring to bring my thoughts to fruition by expressing them on paper in the form of poetry. I delve into fundamental social issues, attempting to answer many questions of the "why does a person do this in a specific way" kind or simply seeking a deeper meaning in seemingly straightforward human matters, as I believe that everything has its reason and specific specifications. On the other hand, I am an exceptionally pragmatic person. I love it when something functions correctly, when I understand its complexity, and when I can break down a given topic into its basic components and enumerate most of its characteristics. I believe that everything in the world is connected in a specific way, starting from quantum relationships on Earth to solving the puzzle of "what exactly is the world we inhabit." If I don't understand something, I am very eager to change that. Although learning constantly shifts its position, and humans rely on the research of thousands of individuals, I love discovering new perspectives on a given paradigm. In my daily life, I mainly surround myself with friends with whom I can discuss such topics – a bit of fantasy, a bit of science, and a bit of light-hearted humor.</div>
        <img src="/public/whoami.svg" />
      </section>
    </div >
  )
}